# Establecer la imagen base
FROM node:14.18.0 as build

# Establecer el directorio de trabajo en la imagen
WORKDIR /app

# Copiar el archivo package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar todos los archivos del proyecto al directorio de trabajo
COPY . .

# Compilar el proyecto
RUN npm run build

# Establecer una nueva imagen base
FROM nginx:1.21.3

# Copiar los archivos de compilación del proyecto al directorio de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]